name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Clone Cosmos
      run: |
        mkdir Cosmos
        mkdir c:/CosmosRun
        cd Cosmos
        git clone https://github.com/aura-systems/Common
        git clone https://github.com/aura-systems/IL2CPU
        git clone https://github.com/aura-systems/Cosmos
        git clone https://github.com/aura-systems/XSharp
    - name: Build Cosmos
      run: |
        cd Cosmos/Cosmos
        msbuild Build.sln /t:Restore
        msbuild Build.sln /maxcpucount /verbosity:normal
    - name: Dotnet Publish
      run: |
        dotnet publish Cosmos\IL2CPU\source\IL2CPU -r win10-x64 -o "c:\CosmosRun\Build\IL2CPU\"
    - name: Copy files
      run: |
        xcopy /Y "Cosmos\Cosmos\Build\syslinux\*.*" "c:\CosmosRun\Build\ISO\"
        xcopy /Y /S "Cosmos\Cosmos\Build\VMware\*" "c:\CosmosRun\Build\VMware\"
        xcopy /Y /S "Cosmos\Cosmos\Build\Tools" "c:\CosmosRun\Build\Tools\"
        xcopy /Y "Cosmos\IL2CPU\source\Cosmos.Core.DebugStub\*.xs" "c:\CosmosRun\XSharp\DebugStub\"
        xcopy /Y /S "Cosmos\Cosmos\Resources\Bochs\*.*" "%ProgramFiles%\Bochs-2.6.8\"
        tree
    - name: Regs add
      run: |
        reg add HKLM\SOFTWARE\WOW6432Node\Cosmos /v UserKit /d "c:\CosmosRun\"
    - name: Build Aura Operating System
      run: |
        cd "Aura Operating System"
        msbuild "Aura_OS.sln" /t:Restore
        msbuild "Aura_OS.sln" /maxcpucount
    - name: Test
      run: dotnet test --no-restore --verbosity normal
